### ISSUE TITLE
wrong vagrant commmand

### ISSUE THREAD

**Issue by natebrennand** [squidarth/Devfest-Environment-Setup#1]
`vagrant hal`t --> `vagrant reload`

https://github.com/squidarth/Devfest-Environment-Setup/blob/gh-pages/index.html#L230

**Comment by squidarth** [comment]
thanks . fixed in https://github.com/squidarth/Devfest-Environment-Setup/commit/550aa1248d6dec3f5d65e89fb05dd446534daffb
